Catalog duplication
artemSologub/ithillel pull request #3
Opened 2024-05-01 17:58 UTC by artemSologub

2024-05-01 19:08 UTC, evhenious commented on source/test-file1.txt
Пункт завдання №1: "...створити два каталоги, і додати в gitignore для них пару строк **по зразку** - щоб можна було закомітити самі каталоги, але далі щоб гіт ігнорив весь контент що буде всередині" 
Щось у тебе пішло не так. В пулріквесті не повинно буди жодного контента в папках source і target, за виключенням файліків gitkeep. Навіть якщо фізично у тебе локально там інші файли будуть

А проблема в тому, що ти от сюда просто скопіпастив мій приклад, не помінявши згідно умов задачі :)

2024-05-01 19:11 UTC, evhenious commented on file_sync.js
> +  return {
Тобі додаткове завдання - почитати статейку отут http://callbackhell.com/ і спробувати покращити свій код

2024-05-01 19:15 UTC, evhenious commented on file_sync.js
> +                    });
Виходить занадто багато рівнів вклденості в коді - це складно сприймати і підтримувати. Самі колбеки це добре, але не варто покладатись повністю на них і анонімні функції створені просто на місцях

2024-05-01 19:20 UTC, evhenious commented on file_sync.js
> +      fileSync().copyCatalog(sourceFolder, targetFolder);
Перший пункт як спростити цей код: не загортати все в функцію `fileSync` і не повертати все як об'єкт - реально немає сенсу. Просто зроби окремі функції start, copyCatalog і так далі. Одразу все стане набагато простіше і прозоріше

2024-05-01 19:26 UTC, evhenious commented on file_sync.js
> +                    logger.warn('File exists!');
Непогано буде писати який саме файл - бо інакше, уяви - 5 файлів вже є, буде 5 однакових повідомлень без жодного натяку про що це за файли :)

2024-05-01 19:29 UTC, evhenious requested changes
Поправ будь ласка gitignore, щоб нові строки в ньому мали відношення саме до наших каталогів source і target.

І головне - спробуй спростити свій код (дивись всі коментарі). Так по функціоналу працює, але читати і сприймати важкенько

2024-05-02 13:50 UTC, artemSologub commented on file_sync.js
> +                    logger.warn('File exists!');
done

2024-05-02 13:50 UTC, artemSologub commented on file_sync.js
> +      fileSync().copyCatalog(sourceFolder, targetFolder);
done

2024-05-02 13:50 UTC, artemSologub commented on file_sync.js
> +                    });
done

2024-05-02 13:50 UTC, artemSologub commented on file_sync.js
> +  return {
done

2024-05-02 13:50 UTC, artemSologub commented on source/test-file1.txt
done

2024-05-02 18:04 UTC, evhenious approved these changes

2024-05-02 18:04 UTC, merged